CustomUserModel/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('customuser.urls')),
]

customuser/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from . import views

urlpatterns = [
    url(r'^$', views.welcome_page, name='welcome_page'),#settignup homepage
    url(r'^register/$', views.registration_page, name='registration'),#custom Reg template
    url(r'^login/$', views.login_page, name='login'),#custom Login template
    url(r'^logout/$', auth_views.logout, {'template_name': 'customuser/logout.html'}, name='logout'),#custom template#system defined
    url(r'^user/(?P<pk>\d+)/verify/$', views.verify_user, name='verify_user'),
    url(r'^profile/$', views.user_profile, name='profile'),#custom Reg template
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

customuser/models.py
from django.db import models

from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import models as auth_models

from .managers import UserManager
# Create your models here.
class User(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)

    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    user_type = models.CharField(_('user type'), max_length=10, blank=False,default='guest')

    is_staff = models.BooleanField(_('is staff'), default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ('id', )

    def get_full_name(self):
        #Returns the first_name + last_name.
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        # Returns first_name
        return self.first_name

    def get_date_joined(self):
        # Returns first_name
        return self.date_joined

    def get_date_joined(self):
        # Returns first_name
        return self.date_joined
    #to send email to user for verification link
    def email_user(self, subject, message, from_email=None, **kwargs):
        # Sends an email to this User.
        send_mail(subject, message, from_email, [self.email], **kwargs)

customuser/forms.py
from django import forms
from .models import User
from django.utils.translation import gettext as _
from datetime import date
from datetime import datetime
from django.utils import formats
from django.contrib.auth import forms as auth_forms

class RegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['last_name'].required = True

    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete':'off'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email','password','password2','birth_date','bio','location')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if len(password1) < 8:
            raise forms.ValidationError('Password too short')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def clean_my_date(self):
        birth_date = self.cleaned_data.get('birth_date')
        birth_date = datetime.strptime(birth_date, '%m/%d/%Y')
        if birth_date >= datetime.now():
            raise forms.ValidationError(u'Wrong Date!')
        return birth_date

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class LogInForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete':'off'}))
    class Meta:
        model = User
        fields = ('email', 'password')
    def clean_password(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        if len(password) < 8:
            raise forms.ValidationError('Password too short')
        return password

class UserVerifyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        userpk = kwargs.pop('pk')
        super(UserVerifyForm, self).__init__(*args, **kwargs)
        self.fields['uid'].initial = userpk
    #self.instance.first == self.cleaned_data.get("user")
    uid = forms.IntegerField(widget=forms.HiddenInput)
    class Meta:
        model = User
        fields = ('uid',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class CustomUserProfileForm(forms.ModelForm):
    def __init__(self,user,*args, **kwargs):
        super(CustomUserProfileForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].initial = user.first_name
        self.fields['last_name'].initial = user.last_name
        self.fields['birth_date'].initial = formats.date_format(user.birth_date, "Y-m-d")
        self.fields['bio'].initial = user.bio
        self.fields['location'].initial = user.location
        self.fields['avatar'].initial = user.avatar
    class Meta:
        model = User
        #fields = ('__all__')
        fields = ('first_name','last_name','birth_date','bio','location','avatar')#,'email'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_my_date(self):
        birth_date = self.cleaned_data.get('birth_date')
        birth_date = datetime.strptime(birth_date, '%m/%d/%Y')
        if birth_date >= datetime.now():
            raise forms.ValidationError(u'Wrong Date!')
        return birth_date

class CustomUserPasswordForm(forms.ModelForm):

    uid = forms.IntegerField(widget=forms.HiddenInput)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete':'off'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def __init__(self,user,*args, **kwargs):
        super(CustomUserPasswordForm, self).__init__(*args, **kwargs)
        self.fields['uid'].initial = user.id
    class Meta:
        model = User
        fields = ('uid','password','password2')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if len(password1) < 8:
            raise forms.ValidationError('Password too short')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

customuser/views.py
from django.shortcuts import render, get_object_or_404

from django.utils import timezone
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password

from .forms import *#RegistrationForm, LogInForm, UserVerifyForm, CustomUserProfileForm,CustomUserPasswordForm
from .models import User

# Create your views here.

def welcome_page(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    else:
        user = request.user

        return render(request, 'customuser/index_page.html', {'user_data':user,'page_title':'Welcome Page'})

def registration_page(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)#commit=False
            #'first_name', 'last_name', 'email','bio','location','birth_date'
            # form brings back a plain text string, not an encrypted password
            pw = user.password
            # thus we need to use set password to encrypt the password string
            user.set_password(pw)
            user.date_joined=timezone.now()
            user.is_active=0 #change it via mail verification
            user.is_staff=0
            user.user_type='gen'
            user.avatar=''
            user.save()
            return render(request, 'customuser/register.html', {'formresponse':'congrats','page_title':'Registration'})
        else:
            return render(request, 'customuser/register.html', {'form':form,'page_title':'Registration'})
    form = RegistrationForm()
    return render(request, 'customuser/register.html', {'form':form,'page_title':'Registration'})

def login_page(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect('/profile/')
    else:
        logout(request) #logs out user upon reaching the /login/ page
        email = password = ''

        if request.method == "POST":
            form = LogInForm(request.POST)
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user is not None:

                if user.is_active:#will not work here as authenticate() will already check this
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    form = LogInForm()
                    state = "Your account is not active, please contact the administrator."
                    return render(request, 'customuser/login.html', {'form':form,'formresponse':state,'page_title':'LogIn'})
            else:
                form = LogInForm()
                state = "Your email and/or password were incorrect."
                return render(request, 'customuser/login.html', {'form':form,'formresponse':state,'page_title':'LogIn'})
        else:
            form = LogInForm()
            return render(request, 'customuser/login.html', {'form':form,'page_title':'LogIn'})

def verify_user(request,pk):
    logout(request)
    user = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        form = UserVerifyForm(request.POST, instance=user, pk=pk)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.save()
            return redirect('/', pk=user.pk)

    elif request.method == "GET":
        form = UserVerifyForm(pk=pk)
        return render(request, 'customuser/verify_user.html', {'form': form,'page_title':'Verify User'})

def user_profile(request):
    user = request.user

    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')

    if request.method == "POST":
        if 'update_user_profile' in request.POST:

            form = CustomUserProfileForm(request.user, request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                user = form.save(commit=False)#commit=False
                #user.user = request.user
                user.save()
                return render(request, 'customuser/user_profile.html', {'formresponse':'Profile Updated','page_title':'Profile'})
            else:
                return render(request, 'customuser/user_profile.html', {'form':form,'formresponse':form.errors,'page_title':'Profile'})

        else:
            pswrdform = CustomUserPasswordForm(request.user, request.POST, request.FILES, instance=request.user)
            if pswrdform.is_valid():
                user = pswrdform.save(commit=False)
                pw = user.password
                user.set_password(pw)
                user.save()
                #logout user when password change to login with new password
                return HttpResponseRedirect('/logout/')
                #return render(request, 'customuser/user_profile.html', {'formresponse2':'Password Changed','page_title':'Profile'})
            else:
                return render(request, 'customuser/user_profile.html', {'password_form':pswrdform,'formresponse2':pswrdform.errors,'page_title':'Profile'})

    #user = request.user
    form = CustomUserProfileForm(user=user)
    password_form = CustomUserPasswordForm(user=user)

    return render(request, 'customuser/user_profile.html', {'form':form,'password_form':password_form,'user_data':user,'page_title':'Profile'})

customuser/templates/customuser/base.html
{% load staticfiles %}
<html>
    <head>
        <title>CustomUserModel-{{ page_title }}</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </head>
    <body>
    <div class="page-header">
      <h1><a href="/">dJango Custom User Model</a></h1>
      <div class="row">
        <div class="col-md-12" style="text-align:right;">
        {% if user.is_authenticated %}
        <a href="/profile">Profile</a> | <a href="/logout">LogOut</a>
        {% else %}
        <a href="/login">Login </a> | <a href="/register"> Register </a>
        {% endif %}
        </div>
      </div>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
  </body>
    </body>
</html>

customuser/templates/customuser/index_page.html
{% extends './base.html' %}
{% block content %}
  {% if user.is_authenticated %}
    <h4>Welcome User</h4><br/>
    <p>Name: {{ user_data.get_full_name }}</p>
    <p>Date Joined: {{ user_data.get_date_joined }}</p>
    <p>eMail: {{ user_data.email }}</p>
    <p>User Type: {{ user_data.user_type }}</p>
    <p>Bio: {{ user_data.bio }}</p>
    <p>Location: {{ user_data.location }}</p>
  {% else %}
  <a href="/login">Login </a> | <a href="/register"> Register </a>
  {% endif %}
{% endblock %}

customuser/templates/customuser/login.html
{% extends './base.html' %}
{% block content %}
    <h1>LogIn</h1>
    {% if form %}
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Submit</button>
        {% if formresponse %}
          {{ formresponse }}
        {% endif %}
    </form>
    {% else %}
      {{ formresponse }}
    {% endif %}
{% endblock %}

customuser/templates/customuser/logout.html
{% extends './base.html' %}
{% block content %}
{% endblock %}

customuser/templates/customuser/register.html
{% extends './base.html' %}
{% block content %}
    <h1>New Registration</h1>
    {% if form %}
    <form method="POST" class="post-form"> <!--enctype="multipart/form-data"-->
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="save btn btn-default">Submit</button>
        <script>
        $( function() {
          $( "#id_birth_date" ).datepicker();
        } );
        </script>
    </form>
    {% else %}
      {{ formresponse }}
    {% endif %}

{% endblock %}

customuser/templates/customuser/update_profile.html
{% extends 'blog/base.html' %}
{% block content %}
  <form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Save changes</button>
  </form>
{% endblock %}

customuser/templates/customuser/user_profile.html
{% extends './base.html' %}
{% block content %}
  {% if user.is_authenticated %}
    <!--br><p>First Name: {{ user_data.first_name }}</p>
    <br><p>Last Name: {{ user_data.last_name }}</p>
    <br><p>eMail: {{ user_data.email }}</p>
    <br><p>User Type: {{ user_data.user_type }}</p>
    <br><p>Bio: {{ user_data.bio }}</p-->
    {% if form %}
    <form class="form-horizontal" method="POST" class="post-form" enctype="multipart/form-data"> <!--enctype="multipart/form-data"-->
        <div class="form-group">
          <label for="{{ form.first_name.id_for_label}}">First Name:</label>
          <input type="text" class="form-control" id="{{ form.first_name.id_for_label}}" name="{{ form.first_name.name}}" value="{{ form.first_name.value}}">
        </div>
        <div class="form-group">
          <label for="{{ form.last_name.id_for_label}}">Last Name:</label>
          <input type="text" class="form-control" id="{{ form.last_name.id_for_label}}" name="{{ form.last_name.name}}" value="{{ form.last_name.value}}">
        </div>
        <!--div class="form-group">
          <label for="{{ form.email.id_for_label}}">eMail:</label>
          <input type="email" readonly class="form-control" id="{{ form.email.id_for_label}}" name="{{ form.email.name}}" value="{{ form.email.value}}">
        </div-->
        <div class="form-group">
          <label for="{{ form.birth_date.id_for_label}}">Birth Date:</label>
          <input type="date" class="form-control" id="{{ form.birth_date.id_for_label}}" name="{{ form.birth_date.name}}" value="{{ form.birth_date.value }}">
        </div>

        <div class="form-group">
          <label for="{{ form.avatar.id_for_label}}">Avatar:</label>
            <br/>
            Currently: <img src="/media/{{ form.avatar.value }}" alt="uimage" style="width:100px;">
            <br><a href="/media/{{ form.avatar.value }}">{{ form.avatar.value }}</a>
            <br><label for="avatar-clear_id">Clear</label> <input type="checkbox" name="avatar-clear" id="avatar-clear_id" />
            <br />
            Change:
            <input class="form-control" type="file" name="{{ form.avatar.name }}" id="{{ form.avatar.id_for_label}}" /></td></tr>
        </div>

        <div class="form-group">
          <label for="{{ form.bio.id_for_label}}">Bio:</label>
          <textarea class="form-control" id="{{ form.bio.id_for_label}}" name="{{ form.bio.name}}">{{ form.bio.value }}</textarea>
        </div>
        <div class="form-group">
          <label for="{{ form.location.id_for_label}}">Location:</label>
          <input type="text" class="form-control" id="{{ form.location.id_for_label}}" name="{{ form.location.name}}" value="{{ form.location.value}}">
        </div>
        {% csrf_token %}
        <button type="submit" name="update_user_profile" class="save btn btn-default">Submit</button>
        <script>
        $( function() {
          $( "#id_birth_date" ).datepicker();
        } );
        </script>
        {{ formresponse }}
    </form>
    {% else %}
      {{ formresponse }}
    {% endif %}

    {% if password_form %}
    <br/><br/>
    <h4>Change Password</h4>
    <form class="form-horizontal" method="POST" class="post-form">
      <input type="hidden" name="{{ password_form.uid.name }}" id="{{ password_form.uid.id_for_label }}" value="{{ password_form.uid.value }}">
      <div class="form-group">
        <label for="id_password">Password:</label>
        <input class="form-control" type="password" name="{{ password_form.password.name }}" autocomplete="off" required id="{{ password_form.password.id_for_label }}" /></p>
      </div>
      <div class="form-group">
        <label for="id_password2">Confirm password:</label>
        <input class="form-control" type="password" name="{{ password_form.password2.name }}" required id="{{ password_form.password2.id_for_label }}" /></p>
      </div>
      {% csrf_token %}
      <button type="submit" name="update_user_password" class="save btn btn-default">Submit</button>
    </form>
      {{ formresponse2 }}
    {% else %}
      {{ formresponse2 }}
    {% endif %}

  {% else %}
  <a href="/login">Login </a> | <a href="/register"> Register </a>
  {% endif %}
{% endblock %}

customuser/templates/customuser/verify_user.html
{% extends './base.html' %}

{% block content %}
    <h1>Verify</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Verify</button>
    </form>
{% endblock %}